[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.cppstd=17
compiler.version=8.1
build_type=Release
compiler.libcxx=libstdc++11
compiler.threads=posix
[options]
[build_requires]
[env]
