import os

Decider('timestamp-newer')

conan = SConscript('build/SConscript_conan')

#env_release = Environment(parse_flags='-std=c++17', **conan['conan'])

env_release = Environment(tools=['mingw'], **conan['conan'])
env_release.Append(CXXFLAGS='-std=c++17')
env_release.Program('omega', 'main.cpp')

env_debug = env_release.Clone(CCFLAGS='-g')
d = env_debug.Object('omega-debug', 'main.cpp')
env_debug.Program(d)
