import os

conan = SConscript('build/SConscript_conan')
env = Environment(**conan['conan'])

env.Program(
    'omega',
    'main.cpp',
    parse_flags='-std=c++17',
    #parse_flags='-std=c++17 -lsfml-graphics -lsfml-window -lsfml-system',
    #CPPPATH=['.', '/usr/local/lib/']
)
