# Build tests
import os

Decider('timestamp-newer')

conan = SConscript('../build/SConscript_conan')

env = Environment(parse_flags='-std=c++17', **conan['Catch2'])

SOURCE_FILES = [
  'test_main.cpp',

  'test_vector.cpp',
  '../vector.cpp',
]


env.Program('omega-test', SOURCE_FILES)
